name: Check

on: [push, pull_request]

jobs:
  check:
    name: Build and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check format
        run: pnpm run format:check

      - name: Build with VitePress
        run: pnpm run build
